In [102]:
import numpy as np
import torch
from MultiStage.util import *

# 测试 is_corase_class 函数

In [103]:
x = torch.rand(4,2,3)  # [batch, k, 1024]
print(x)
x = x / x.norm(dim=-1, keepdim=True)
print(x)

tensor([[[0.7895, 0.2996, 0.5930],
         [0.1490, 0.1624, 0.6281]],

        [[0.4370, 0.6370, 0.9540],
         [0.1334, 0.0965, 0.7534]],

        [[0.6093, 0.8006, 0.8598],
         [0.5407, 0.1176, 0.5436]],

        [[0.7620, 0.9003, 0.8044],
         [0.4794, 0.1077, 0.4694]]])
tensor([[[0.7651, 0.2904, 0.5747],
         [0.2238, 0.2439, 0.9436]],

        [[0.3560, 0.5189, 0.7772],
         [0.1730, 0.1251, 0.9769]],

        [[0.4604, 0.6050, 0.6497],
         [0.6970, 0.1516, 0.7008]],

        [[0.5337, 0.6306, 0.5634],
         [0.7055, 0.1585, 0.6908]]])


In [104]:

logits = torch.rand(4,10)
target = torch.randint(0,5,(4,1)).view(-1)
print('logits.topk(5)[1]:\n\t',logits.topk(5)[1])
print('target:\n\t',target)
print(is_corase_class(logits,target,5))

logits.topk(5)[1]:
	 tensor([[1, 9, 2, 7, 6],
        [4, 0, 3, 6, 7],
        [0, 1, 8, 2, 7],
        [9, 0, 8, 6, 4]])
target:
	 tensor([0, 0, 1, 0])
tensor([0, 1, 0])


# list

In [105]:
l = torch.zeros(1000,dtype=torch.long)
l.topk(10)

torch.return_types.topk(
values=tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
indices=tensor([8, 9, 4, 7, 5, 3, 1, 0, 2, 6]))

# imageNet class

In [106]:
imagenet_classes = ["tench", "goldfish", "great white shark", "tiger shark", "hammerhead shark", "electric ray",
                        "stingray", "rooster", "hen", "ostrich", "brambling", "goldfinch", "house finch", "junco",
                        "indigo bunting", "American robin", "bulbul", "jay", "magpie", "chickadee", "American dipper",
                        "kite (bird of prey)", "bald eagle", "vulture", "great grey owl", "fire salamander",
                        "smooth newt", "newt", "spotted salamander", "axolotl", "American bullfrog", "tree frog",
                        "tailed frog", "loggerhead sea turtle", "leatherback sea turtle", "mud turtle", "terrapin",
                        "box turtle", "banded gecko", "green iguana", "Carolina anole",
                        "desert grassland whiptail lizard", "agama", "frilled-necked lizard", "alligator lizard",
                        "Gila monster", "European green lizard", "chameleon", "Komodo dragon", "Nile crocodile",
                        "American alligator", "triceratops", "worm snake", "ring-necked snake",
                        "eastern hog-nosed snake", "smooth green snake", "kingsnake", "garter snake", "water snake",
                        "vine snake", "night snake", "boa constrictor", "African rock python", "Indian cobra",
                        "green mamba", "sea snake", "Saharan horned viper", "eastern diamondback rattlesnake",
                        "sidewinder rattlesnake", "trilobite", "harvestman", "scorpion", "yellow garden spider",
                        "barn spider", "European garden spider", "southern black widow", "tarantula", "wolf spider",
                        "tick", "centipede", "black grouse", "ptarmigan", "ruffed grouse", "prairie grouse", "peafowl",
                        "quail", "partridge", "african grey parrot", "macaw", "sulphur-crested cockatoo", "lorikeet",
                        "coucal", "bee eater", "hornbill", "hummingbird", "jacamar", "toucan", "duck",
                        "red-breasted merganser", "goose", "black swan", "tusker", "echidna", "platypus", "wallaby",
                        "koala", "wombat", "jellyfish", "sea anemone", "brain coral", "flatworm", "nematode", "conch",
                        "snail", "slug", "sea slug", "chiton", "chambered nautilus", "Dungeness crab", "rock crab",
                        "fiddler crab", "red king crab", "American lobster", "spiny lobster", "crayfish", "hermit crab",
                        "isopod", "white stork", "black stork", "spoonbill", "flamingo", "little blue heron",
                        "great egret", "bittern bird", "crane bird", "limpkin", "common gallinule", "American coot",
                        "bustard", "ruddy turnstone", "dunlin", "common redshank", "dowitcher", "oystercatcher",
                        "pelican", "king penguin", "albatross", "grey whale", "killer whale", "dugong", "sea lion",
                        "Chihuahua", "Japanese Chin", "Maltese", "Pekingese", "Shih Tzu", "King Charles Spaniel",
                        "Papillon", "toy terrier", "Rhodesian Ridgeback", "Afghan Hound", "Basset Hound", "Beagle",
                        "Bloodhound", "Bluetick Coonhound", "Black and Tan Coonhound", "Treeing Walker Coonhound",
                        "English foxhound", "Redbone Coonhound", "borzoi", "Irish Wolfhound", "Italian Greyhound",
                        "Whippet", "Ibizan Hound", "Norwegian Elkhound", "Otterhound", "Saluki", "Scottish Deerhound",
                        "Weimaraner", "Staffordshire Bull Terrier", "American Staffordshire Terrier",
                        "Bedlington Terrier", "Border Terrier", "Kerry Blue Terrier", "Irish Terrier",
                        "Norfolk Terrier", "Norwich Terrier", "Yorkshire Terrier", "Wire Fox Terrier",
                        "Lakeland Terrier", "Sealyham Terrier", "Airedale Terrier", "Cairn Terrier",
                        "Australian Terrier", "Dandie Dinmont Terrier", "Boston Terrier", "Miniature Schnauzer",
                        "Giant Schnauzer", "Standard Schnauzer", "Scottish Terrier", "Tibetan Terrier",
                        "Australian Silky Terrier", "Soft-coated Wheaten Terrier", "West Highland White Terrier",
                        "Lhasa Apso", "Flat-Coated Retriever", "Curly-coated Retriever", "Golden Retriever",
                        "Labrador Retriever", "Chesapeake Bay Retriever", "German Shorthaired Pointer", "Vizsla",
                        "English Setter", "Irish Setter", "Gordon Setter", "Brittany dog", "Clumber Spaniel",
                        "English Springer Spaniel", "Welsh Springer Spaniel", "Cocker Spaniel", "Sussex Spaniel",
                        "Irish Water Spaniel", "Kuvasz", "Schipperke", "Groenendael dog", "Malinois", "Briard",
                        "Australian Kelpie", "Komondor", "Old English Sheepdog", "Shetland Sheepdog", "collie",
                        "Border Collie", "Bouvier des Flandres dog", "Rottweiler", "German Shepherd Dog", "Dobermann",
                        "Miniature Pinscher", "Greater Swiss Mountain Dog", "Bernese Mountain Dog",
                        "Appenzeller Sennenhund", "Entlebucher Sennenhund", "Boxer", "Bullmastiff", "Tibetan Mastiff",
                        "French Bulldog", "Great Dane", "St. Bernard", "husky", "Alaskan Malamute", "Siberian Husky",
                        "Dalmatian", "Affenpinscher", "Basenji", "pug", "Leonberger", "Newfoundland dog",
                        "Great Pyrenees dog", "Samoyed", "Pomeranian", "Chow Chow", "Keeshond", "brussels griffon",
                        "Pembroke Welsh Corgi", "Cardigan Welsh Corgi", "Toy Poodle", "Miniature Poodle",
                        "Standard Poodle", "Mexican hairless dog (xoloitzcuintli)", "grey wolf", "Alaskan tundra wolf",
                        "red wolf or maned wolf", "coyote", "dingo", "dhole", "African wild dog", "hyena", "red fox",
                        "kit fox", "Arctic fox", "grey fox", "tabby cat", "tiger cat", "Persian cat", "Siamese cat",
                        "Egyptian Mau", "cougar", "lynx", "leopard", "snow leopard", "jaguar", "lion", "tiger",
                        "cheetah", "brown bear", "American black bear", "polar bear", "sloth bear", "mongoose",
                        "meerkat", "tiger beetle", "ladybug", "ground beetle", "longhorn beetle", "leaf beetle",
                        "dung beetle", "rhinoceros beetle", "weevil", "fly", "bee", "ant", "grasshopper",
                        "cricket insect", "stick insect", "cockroach", "praying mantis", "cicada", "leafhopper",
                        "lacewing", "dragonfly", "damselfly", "red admiral butterfly", "ringlet butterfly",
                        "monarch butterfly", "small white butterfly", "sulphur butterfly", "gossamer-winged butterfly",
                        "starfish", "sea urchin", "sea cucumber", "cottontail rabbit", "hare", "Angora rabbit",
                        "hamster", "porcupine", "fox squirrel", "marmot", "beaver", "guinea pig", "common sorrel horse",
                        "zebra", "pig", "wild boar", "warthog", "hippopotamus", "ox", "water buffalo", "bison",
                        "ram (adult male sheep)", "bighorn sheep", "Alpine ibex", "hartebeest", "impala (antelope)",
                        "gazelle", "arabian camel", "llama", "weasel", "mink", "European polecat",
                        "black-footed ferret", "otter", "skunk", "badger", "armadillo", "three-toed sloth", "orangutan",
                        "gorilla", "chimpanzee", "gibbon", "siamang", "guenon", "patas monkey", "baboon", "macaque",
                        "langur", "black-and-white colobus", "proboscis monkey", "marmoset", "white-headed capuchin",
                        "howler monkey", "titi monkey", "Geoffroy's spider monkey", "common squirrel monkey",
                        "ring-tailed lemur", "indri", "Asian elephant", "African bush elephant", "red panda",
                        "giant panda", "snoek fish", "eel", "silver salmon", "rock beauty fish", "clownfish",
                        "sturgeon", "gar fish", "lionfish", "pufferfish", "abacus", "abaya", "academic gown",
                        "accordion", "acoustic guitar", "aircraft carrier", "airliner", "airship", "altar", "ambulance",
                        "amphibious vehicle", "analog clock", "apiary", "apron", "trash can", "assault rifle",
                        "backpack", "bakery", "balance beam", "balloon", "ballpoint pen", "Band-Aid", "banjo",
                        "baluster / handrail", "barbell", "barber chair", "barbershop", "barn", "barometer", "barrel",
                        "wheelbarrow", "baseball", "basketball", "bassinet", "bassoon", "swimming cap", "bath towel",
                        "bathtub", "station wagon", "lighthouse", "beaker", "military hat (bearskin or shako)",
                        "beer bottle", "beer glass", "bell tower", "baby bib", "tandem bicycle", "bikini",
                        "ring binder", "binoculars", "birdhouse", "boathouse", "bobsleigh", "bolo tie", "poke bonnet",
                        "bookcase", "bookstore", "bottle cap", "hunting bow", "bow tie", "brass memorial plaque", "bra",
                        "breakwater", "breastplate", "broom", "bucket", "buckle", "bulletproof vest",
                        "high-speed train", "butcher shop", "taxicab", "cauldron", "candle", "cannon", "canoe",
                        "can opener", "cardigan", "car mirror", "carousel", "tool kit", "cardboard box / carton",
                        "car wheel", "automated teller machine", "cassette", "cassette player", "castle", "catamaran",
                        "CD player", "cello", "mobile phone", "chain", "chain-link fence", "chain mail", "chainsaw",
                        "storage chest", "chiffonier", "bell or wind chime", "china cabinet", "Christmas stocking",
                        "church", "movie theater", "cleaver", "cliff dwelling", "cloak", "clogs", "cocktail shaker",
                        "coffee mug", "coffeemaker", "spiral or coil", "combination lock", "computer keyboard",
                        "candy store", "container ship", "convertible", "corkscrew", "cornet", "cowboy boot",
                        "cowboy hat", "cradle", "construction crane", "crash helmet", "crate", "infant bed",
                        "Crock Pot", "croquet ball", "crutch", "cuirass", "dam", "desk", "desktop computer",
                        "rotary dial telephone", "diaper", "digital clock", "digital watch", "dining table",
                        "dishcloth", "dishwasher", "disc brake", "dock", "dog sled", "dome", "doormat", "drilling rig",
                        "drum", "drumstick", "dumbbell", "Dutch oven", "electric fan", "electric guitar",
                        "electric locomotive", "entertainment center", "envelope", "espresso machine", "face powder",
                        "feather boa", "filing cabinet", "fireboat", "fire truck", "fire screen", "flagpole", "flute",
                        "folding chair", "football helmet", "forklift", "fountain", "fountain pen", "four-poster bed",
                        "freight car", "French horn", "frying pan", "fur coat", "garbage truck",
                        "gas mask or respirator", "gas pump", "goblet", "go-kart", "golf ball", "golf cart", "gondola",
                        "gong", "gown", "grand piano", "greenhouse", "radiator grille", "grocery store", "guillotine",
                        "hair clip", "hair spray", "half-track", "hammer", "hamper", "hair dryer", "hand-held computer",
                        "handkerchief", "hard disk drive", "harmonica", "harp", "combine harvester", "hatchet",
                        "holster", "home theater", "honeycomb", "hook", "hoop skirt", "gymnastic horizontal bar",
                        "horse-drawn vehicle", "hourglass", "iPod", "clothes iron", "carved pumpkin", "jeans", "jeep",
                        "T-shirt", "jigsaw puzzle", "rickshaw", "joystick", "kimono", "knee pad", "knot", "lab coat",
                        "ladle", "lampshade", "laptop computer", "lawn mower", "lens cap", "letter opener", "library",
                        "lifeboat", "lighter", "limousine", "ocean liner", "lipstick", "slip-on shoe", "lotion",
                        "music speaker", "loupe magnifying glass", "sawmill", "magnetic compass", "messenger bag",
                        "mailbox", "tights", "one-piece bathing suit", "manhole cover", "maraca", "marimba", "mask",
                        "matchstick", "maypole", "maze", "measuring cup", "medicine cabinet", "megalith", "microphone",
                        "microwave oven", "military uniform", "milk can", "minibus", "miniskirt", "minivan", "missile",
                        "mitten", "mixing bowl", "mobile home", "ford model t", "modem", "monastery", "monitor",
                        "moped", "mortar and pestle", "graduation cap", "mosque", "mosquito net", "vespa",
                        "mountain bike", "tent", "computer mouse", "mousetrap", "moving van", "muzzle", "metal nail",
                        "neck brace", "necklace", "baby pacifier", "notebook computer", "obelisk", "oboe", "ocarina",
                        "odometer", "oil filter", "pipe organ", "oscilloscope", "overskirt", "bullock cart",
                        "oxygen mask", "product packet / packaging", "paddle", "paddle wheel", "padlock", "paintbrush",
                        "pajamas", "palace", "pan flute", "paper towel", "parachute", "parallel bars", "park bench",
                        "parking meter", "railroad car", "patio", "payphone", "pedestal", "pencil case",
                        "pencil sharpener", "perfume", "Petri dish", "photocopier", "plectrum", "Pickelhaube",
                        "picket fence", "pickup truck", "pier", "piggy bank", "pill bottle", "pillow", "ping-pong ball",
                        "pinwheel", "pirate ship", "drink pitcher", "block plane", "planetarium", "plastic bag",
                        "plate rack", "farm plow", "plunger", "Polaroid camera", "pole", "police van", "poncho",
                        "pool table", "soda bottle", "plant pot", "potter's wheel", "power drill", "prayer rug",
                        "printer", "prison", "missile", "projector", "hockey puck", "punching bag", "purse", "quill",
                        "quilt", "race car", "racket", "radiator", "radio", "radio telescope", "rain barrel",
                        "recreational vehicle", "fishing casting reel", "reflex camera", "refrigerator",
                        "remote control", "restaurant", "revolver", "rifle", "rocking chair", "rotisserie", "eraser",
                        "rugby ball", "ruler measuring stick", "sneaker", "safe", "safety pin", "salt shaker", "sandal",
                        "sarong", "saxophone", "scabbard", "weighing scale", "school bus", "schooner", "scoreboard",
                        "CRT monitor", "screw", "screwdriver", "seat belt", "sewing machine", "shield", "shoe store",
                        "shoji screen / room divider", "shopping basket", "shopping cart", "shovel", "shower cap",
                        "shower curtain", "ski", "balaclava ski mask", "sleeping bag", "slide rule", "sliding door",
                        "slot machine", "snorkel", "snowmobile", "snowplow", "soap dispenser", "soccer ball", "sock",
                        "solar thermal collector", "sombrero", "soup bowl", "keyboard space bar", "space heater",
                        "space shuttle", "spatula", "motorboat", "spider web", "spindle", "sports car", "spotlight",
                        "stage", "steam locomotive", "through arch bridge", "steel drum", "stethoscope", "scarf",
                        "stone wall", "stopwatch", "stove", "strainer", "tram", "stretcher", "couch", "stupa",
                        "submarine", "suit", "sundial", "sunglasses", "sunglasses", "sunscreen", "suspension bridge",
                        "mop", "sweatshirt", "swim trunks / shorts", "swing", "electrical switch", "syringe",
                        "table lamp", "tank", "tape player", "teapot", "teddy bear", "television", "tennis ball",
                        "thatched roof", "front curtain", "thimble", "threshing machine", "throne", "tile roof",
                        "toaster", "tobacco shop", "toilet seat", "torch", "totem pole", "tow truck", "toy store",
                        "tractor", "semi-trailer truck", "tray", "trench coat", "tricycle", "trimaran", "tripod",
                        "triumphal arch", "trolleybus", "trombone", "hot tub", "turnstile", "typewriter keyboard",
                        "umbrella", "unicycle", "upright piano", "vacuum cleaner", "vase", "vaulted or arched ceiling",
                        "velvet fabric", "vending machine", "vestment", "viaduct", "violin", "volleyball",
                        "waffle iron", "wall clock", "wallet", "wardrobe", "military aircraft", "sink",
                        "washing machine", "water bottle", "water jug", "water tower", "whiskey jug", "whistle",
                        "hair wig", "window screen", "window shade", "Windsor tie", "wine bottle", "airplane wing",
                        "wok", "wooden spoon", "wool", "split-rail fence", "shipwreck", "sailboat", "yurt", "website",
                        "comic book", "crossword", "traffic or street sign", "traffic light", "dust jacket", "menu",
                        "plate", "guacamole", "consomme", "hot pot", "trifle", "ice cream", "popsicle", "baguette",
                        "bagel", "pretzel", "cheeseburger", "hot dog", "mashed potatoes", "cabbage", "broccoli",
                        "cauliflower", "zucchini", "spaghetti squash", "acorn squash", "butternut squash", "cucumber",
                        "artichoke", "bell pepper", "cardoon", "mushroom", "Granny Smith apple", "strawberry", "orange",
                        "lemon", "fig", "pineapple", "banana", "jackfruit", "cherimoya (custard apple)", "pomegranate",
                        "hay", "carbonara", "chocolate syrup", "dough", "meatloaf", "pizza", "pot pie", "burrito",
                        "red wine", "espresso", "tea cup", "eggnog", "mountain", "bubble", "cliff", "coral reef",
                        "geyser", "lakeshore", "promontory", "sandbar", "beach", "valley", "volcano", "baseball player",
                        "bridegroom", "scuba diver", "rapeseed", "daisy", "yellow lady's slipper", "corn", "acorn",
                        "rose hip", "horse chestnut seed", "coral fungus", "agaric", "gyromitra", "stinkhorn mushroom",
                        "earth star fungus", "hen of the woods mushroom", "bolete", "corn cob", "toilet paper"]

In [107]:
print(imagenet_classes[68])

sidewinder rattlesnake


In [108]:
topK_corase_classes_list = torch.load('/data/luowei/missing_modality/Tip-Adapter-Multi-Stage/checkpoints/classed_indices.pt')
print(len(topK_corase_classes_list))
print(topK_corase_classes_list.topk(100))

top100 = topK_corase_classes_list.topk(100)[1]

if 60 in topK_corase_classes_list.topk(100)[1]:
    print('1')
else:
    print(0)


1000
torch.return_types.topk(
values=tensor([11, 10,  9,  9,  8,  8,  8,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
         7,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
         6,  6,  6,  6,  6,  6,  6,  6,  6,  5,  5,  5,  5,  5,  5,  5,  5,  5,
         5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
         5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
         5,  5,  5,  5,  5,  5,  5,  5,  5,  5]),
indices=tensor([380, 240, 516,  66, 157, 840,  54, 526,  73, 733,  68, 222, 219, 567,
        304, 418, 469, 342, 487, 408, 663, 826, 664, 241, 246, 725, 381, 845,
        848, 749, 512, 153, 173, 488, 527, 189, 542, 893, 748, 438, 231, 947,
        461, 204, 193, 647, 220, 730, 227, 596, 229, 810,  86, 373, 631, 644,
        421, 419, 584, 885, 744, 256, 264, 618, 266, 282, 662, 262, 267,  26,
        636, 883, 771, 318, 341, 910, 911, 164, 134, 187, 348, 192, 777, 194,
        200, 305, 390, 689, 163, 509,

# save tensor

In [109]:
path = '/data/luowei/missing_modality/Tip-Adapter-Multi-Stage/checkpoints/test.pt'
a = torch.tensor([[1,2,3],[1,2,3]])
torch.save(a,path)

b = torch.load(path)
print(b.shape)
b = b.T
print(b.shape)


torch.Size([2, 3])
torch.Size([3, 2])


# 矩阵相乘

In [110]:
a = torch.rand(2,3,4)
b = torch.rand(2,3)
b = b.unsqueeze(1)
# print(a)
# print(b)
res = b @ a
# res = torch.matmul(b,a)
res = res.squeeze(1)
print(res.shape)
print(res)

torch.Size([2, 4])
tensor([[0.3363, 0.4026, 0.2525, 0.3775],
        [0.8872, 0.9971, 0.8307, 0.2898]])


In [111]:
a = torch.ones(3,4)
b = torch.ones(5,4,2)
res = torch.matmul(a, b)
print(res.shape)

torch.Size([5, 3, 2])


# list获取元素下标

In [112]:
a =  [1,2,3,4,5]
print(a.index(2)) 
print(np.random.randint(0,5))

1
3


# 测试 find_topk_classes（）

In [113]:
def find_topk_classes(logits:torch.Tensor, target:torch.Tensor, classNames:list, zeroshot_weights_dict, k:int = 5):
    logits = logits.to(torch.float32) # 转精度
    indices = logits.topk(k)[1] # [batch , k]

    offset = k

    # 1. new target
    new_target = [] # [batch]
    # 对于一个样本，如果其topk中有GT，则将其新标签定义为topK中GT的下标
    # 如果其topK没有GT，那么就在[0,K)中随机赋值一个新标签给该样本 TODO
    for index, topK_i in enumerate(indices):
        target_i = target[index]
        if target_i in topK_i:
            new_target_i = ((topK_i == target_i).nonzero(as_tuple=True)[0]).item()
        else:
            new_target_i = target_i + offset
        new_target.append(new_target_i)

    new_target = torch.tensor(new_target).cuda()
    
    # 2. class embedding  
    class_embeddings = [] # [batch, k, 1024]
    for index, indices_i in enumerate(indices):
        embeddings = []
        for i in indices_i:
            name = classNames[i]
            embeddings.append(zeroshot_weights_dict[name])
        
        # add neg embedding
        if new_target[index] >= k: # 说明topK中没有GT
            # 获取GT的类别下标
            extra_index = new_target[index] - offset
            print(f'index:{index},pos, extra_index:{extra_index}')
            new_target[index] = k # 把GT作为第k+1个class embedding
        else:
            # 随机从TopK以外的下标中取一个作为负类样本
            while(1):
                extra_index = np.random.randint(0,len(classNames))
                if extra_index not in indices_i:
                    print(f'index:{index},neg, extra_index:{extra_index}')
                    break
        neg_name = classNames[extra_index]
        embeddings.append(zeroshot_weights_dict[neg_name])
        embeddings = torch.stack(embeddings) # [k+1, 1024]
        class_embeddings.append(embeddings)
    class_embeddings = torch.stack(class_embeddings)


    return class_embeddings, new_target

In [114]:
zeroshot_weights_dict = torch.load('/data/luowei/missing_modality/Tip-Adapter-Multi-Stage/checkpoints/zeroshot_weights_dict.pt')

In [115]:
logits = torch.rand(4,10)
target = torch.randint(0,10,(4,1)).view(-1)
class_embeddings, new_target = find_topk_classes(logits,target,imagenet_classes,zeroshot_weights_dict,5)

index:0,pos, extra_index:0
index:1,pos, extra_index:3
index:2,pos, extra_index:4
index:3,neg, extra_index:378


In [116]:
print(logits.topk(10)[1])
print('target:\n\t',target)
print('new_target:\n\t',new_target)

tensor([[6, 9, 3, 7, 2, 0, 5, 8, 4, 1],
        [7, 5, 8, 6, 2, 9, 0, 3, 1, 4],
        [7, 5, 6, 2, 0, 8, 9, 1, 3, 4],
        [1, 2, 4, 8, 0, 9, 5, 7, 3, 6]])
target:
	 tensor([0, 3, 4, 0])
new_target:
	 tensor([5, 5, 5, 4], device='cuda:0')


# topK_indices_to_mask

In [117]:
def topK_indices_to_mask(batch_topk_indices:torch.tensor, class_num = 1000, shot = 16):
    batch_size = batch_topk_indices.shape[0]
    masks_class = torch.zeros(batch_size, class_num)

    for index, indices in enumerate(batch_topk_indices):
        for i in indices:
            masks_class[index][i] = 1
    
    
    masks_sample = masks_class.unsqueeze(2)
    masks_sample = masks_sample.repeat(1,1,16)
    masks_sample = masks_sample.view(batch,-1)


    return masks_sample, masks_class

In [118]:
indices = torch.randint(0,1000,(256,5))
class_num = 1000
shot = 16
print(indices)
masks_sample, masks_class = topK_indices_to_mask(indices, class_num, shot)
print(masks_class)
print(masks_sample)


tensor([[627, 492, 487,  84, 538],
        [918, 678, 874, 216, 130],
        [500, 144,  88, 679, 180],
        ...,
        [839, 867, 250, 599, 209],
        [540, 957, 684, 645, 271],
        [135, 745, 967, 166,  99]])
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])


# 矩阵乘法

In [119]:
a = torch.rand(2,2)
b = torch.rand(2,2)
res = a * b 
print(a)
print(b)
print(res.shape)
print(res)

tensor([[0.2238, 0.4009],
        [0.2332, 0.5936]])
tensor([[0.0653, 0.7109],
        [0.8927, 0.4835]])
torch.Size([2, 2])
tensor([[0.0146, 0.2850],
        [0.2082, 0.2870]])


# repeat

In [120]:
batch = 256
class_num = 1000
a = torch.randint(0,2,(batch,class_num))
print(a.shape)
b = a.unsqueeze(2)
b = b.repeat(1,1,16)
b = b.view(batch,-1)
print(b.shape)

torch.Size([256, 1000])
torch.Size([256, 16000])


# Mask的顺序

In [158]:
# logits : [batch, class_num]
# image_features : [batch, image_dim]
# zeroshot_weights : [image_dim, class_num]
# masks_class : [batch, class_num]

batch = 16
image_dim = 1024
class_num = 10

image_features = torch.rand(batch,image_dim,dtype=torch.float16)
image_features = image_features / image_features.norm(dim=-1,keepdim=True)

zeroshot_weights = torch.rand(image_dim,class_num,dtype=torch.float16)
zeroshot_weights = zeroshot_weights / zeroshot_weights.norm(dim=-1,keepdim=True)

masks_class = torch.randint(0,2,(batch, class_num),dtype=torch.float16)
print(masks_class)

# 计算方式 1
logits1 = (image_features @ zeroshot_weights) * masks_class # 盖掉topk以外类别的prompts
print(logits1[0])

# 计算方式 2
zeroshot_weights = zeroshot_weights.T.unsqueeze(0).repeat(batch,1,1) # [batch, class_num, image_dim]
masks_class = masks_class.unsqueeze(2)
batch_masked_zeroshot_weights = masks_class * zeroshot_weights # [batch, class_num, image_dim]
batch_masked_zeroshot_weights = batch_masked_zeroshot_weights.permute(0,2,1) # [batch, image_dim, class_num]
image_features = image_features.unsqueeze(1) # [batch, 1, image_dim]
logits2 = image_features @ batch_masked_zeroshot_weights # [batch, 1, image_dim] @ [batch, image_dim, class_num] = [batch, 1, class_num]
logits2 = logits2.squeeze(1) # [batch, 1, class_num]->[batch, class_num]
print(logits2.shape)
print(logits2[0]) # [batch, class_num]


print(torch.sum(logits1) == torch.sum(logits2))

tensor([[0., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
        [0., 0., 1., 0., 0., 1., 0., 1., 1., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 1., 0., 0., 0., 1., 0., 0.],
        [1., 1., 0., 1., 1., 1., 1., 0., 0., 1.],
        [0., 0., 0., 1., 1., 0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 1., 0., 1., 0., 0., 0., 1.],
        [1., 1., 0., 0., 1., 1., 0., 0., 1., 0.],
        [0., 0., 1., 0., 1., 1., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1., 0., 1., 1., 1., 0.],
        [1., 0., 1., 0., 1., 0., 0., 1., 0., 0.],
        [0., 0., 1., 1., 0., 1., 0., 1., 0., 0.],
        [1., 0., 0., 1., 1., 0., 1., 1., 0., 1.]], dtype=torch.float16)
tensor([0.0000, 7.6250, 7.8008, 7.6602, 0.0000, 7.5586, 7.7656, 7.5859, 7.6914,
        7.8945], dtype=torch.float16)
torch.Size([16, 10])
tensor([0.0000, 7.6250, 7.8008, 7.6602,