In [15]:
import torch

In [16]:
batch = 4
seq_len = 2
dim = 2
a=torch.rand(batch,seq_len,dim)
print(a)
b=torch.rand(batch,1,dim)
print(b)
res = a + b
print(res)

tensor([[[0.0986, 0.3325],
         [0.8410, 0.1654]],

        [[0.7595, 0.5923],
         [0.9743, 0.4422]],

        [[0.1488, 0.5953],
         [0.7227, 0.9367]],

        [[0.0654, 0.7041],
         [0.3643, 0.3125]]])
tensor([[[0.9101, 0.2547]],

        [[0.8328, 0.7735]],

        [[0.4880, 0.2501]],

        [[0.5735, 0.5823]]])
tensor([[[1.0087, 0.5872],
         [1.7510, 0.4201]],

        [[1.5923, 1.3658],
         [1.8071, 1.2157]],

        [[0.6367, 0.8454],
         [1.2107, 1.1868]],

        [[0.6390, 1.2864],
         [0.9378, 0.8948]]])


In [31]:
output = torch.rand(4,5)
target = torch.randint(0,5,(4,1))
pred = output.topk(5, 1, True, True)[1].t()
expand_target = target.view(1, -1).expand_as(pred)
correct = pred.eq(expand_target)

In [34]:
output = torch.rand(4,5)
top1 = output.topk(1)[1]
print(top1[0])

tensor([4])
